name: college_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  firebase_core: 
  firebase_database:
  firebase_auth: 
  flutter_secure_storage:
  firebase_storage: ^11.5.3
  curved_navigation_bar: ^1.0.3
  flutter_svg:
  loading_animation_widget:
  dashed_circular_progress_bar: ^0.0.6
  table_calendar: ^3.1.1
  flutter_form_builder:
  timelines: ^0.1.0
  simple_gradient_text: ^1.3.0
  connectivity_plus:
  permission_handler:
  agora_uikit:
  agora_rtc_engine:
  device_info_plus: ^10.1.0
  file_picker: ^8.0.3
  chewie: ^1.8.1
  video_player: ^2.8.6
  flutter_downloader: ^1.11.7
  #required for webview class
  webview_flutter: 3.0.4
  google_fonts:
  http:
  uuid:
  shared_preferences:
  cloud_firestore: 
  ionicons:
  animations: 
  razorpay_flutter: 
  hexcolor: 
  bottom_navy_bar: 
  url_launcher: 
  image_picker: 
  connectivity: 
  provider: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/top_header.png
    - assets/no-internet.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.png
    - assets/images/6.jpg
    - assets/images/icon/1.png
    - assets/images/back_arrow.svg
    - assets/images/team_illustration.png
    - assets/images/icon/logo.png
    - assets/images/img-1.png
    - assets/images/img-2.jpg
    - assets/images/img-3.png
    - assets/svg/checkbox.svg
    - assets/images/kartik.jpg
    - assets/images/paras.jpg
  fonts:
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/mo_re.ttf
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/mo_me.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
    - family: Cardo
      fonts:
        - asset: assets/fonts/Cardo-Bold.ttf
        - asset: assets/fonts/Cardo-Regular.ttf
        - asset: assets/fonts/Cardo-Italic.ttf

    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Bold.ttf